---
- id: 1
  name: News
  children:
    - id: 2
      name: University
      children:
        - id: 3
          name: Academics
        - id: 4
          name: Board of Trustees
    - id: 5
      new_id: 3
      name: Merged
    - id: 10
      name: Archived
      archived: true
- id: 6
  name: Sports
- id: 7
  name: Opinion
- id: 8
  name: Recess
- id: 9
  name: Towerview
