---
aws:
  access_key_id: access_key
  secret_access_key: secret_key
  bucket: chrondev
content_cdn: cdn.example.com
disqus:
  api_key: disqus_key
  shortname: chrondev
domain: lvh.me
mailchimp:
  ad_image: pikachu.png
  ad_href: http://www.example.com
  api_key: mailchimp_key
  from_email: no-reply@example.com
  from_name: Duke Chronicle
  list_id: list_id
  template_id: 429
taxonomy:
  - name: News
    children:
      - name: University
        children:
          - name: Academics
          - name: Board of Trustees
  - name: Sports
  - name: Opinion
  - name: Recess
  - name: Towerview
